# Generated by Django 5.2 on 2025-10-09 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sessionapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.CharField(
                help_text="Nom de la salle (lettres et chiffres seulement)",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le nom de la salle ne peut contenir que des lettres, chiffres et espaces.",
                        regex="^[a-zA-Z0-9\\s]+$",
                    )
                ],
            ),
        ),
    ]
