# Generated by Django 5.2 on 2025-10-09 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Conferenceapp", "0004_alter_organizing_commiteee_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=30,
                        message="La description doit contenir au moins 30 caractères.",
                    )
                ]
            ),
        ),
    ]
