# Generated by Django 5.2 on 2025-10-09 12:47

import Conferenceapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Conferenceapp", "0005_alter_conference_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="keyword",
            field=models.CharField(
                help_text="Mots-clés séparés par des virgules (maximum 10)",
                max_length=200,
                validators=[Conferenceapp.models.validate_keywords],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="paper",
            field=models.FileField(
                help_text="Seuls les fichiers PDF sont autorisés",
                upload_to="papers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
