# Generated by Django 5.2 on 2025-10-09 11:46

import django.core.validators
import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, validators=[userapp.models.verify_email]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seules les lettres, espaces, tirets et apostrophes sont autorisés.",
                        regex="^[a-zA-Z\\s\\-\\']+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seules les lettres, espaces, tirets et apostrophes sont autorisés.",
                        regex="^[a-zA-Z\\s\\-\\']+$",
                    )
                ],
            ),
        ),
    ]
